sudo: required
services:
  - docker
before_install:
  - docker-compose build
  - docker-compose up -d

script:
  - docker-compose run web python manage.py test
branches:
  only:
    - master
    - develop
