version: "3.3"
services:
  web:
    build: .
    ports:
      - "8000:8000"
    networks:
      - main
    depends_on:
      - db
  db:
    image: mysql:5.7
    networks:
      - main
    ports:
      - "3306:3306"
networks:
  main:
